# Site settings
title: "Proyecto de Introducción a la Ingeniería en Software" 
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
Biografía
title_description: "Mi nombre es Diego Carvajal, Tengo 21 años. Nací el 17 de octubre del año 1998 en la ciudad de Guayaquil. Desde muy pequeño me gustó aprender nuevas cosas, entre lo principal es mi gusto por los idiomas; actualmente tengo un nivel intermedio-avanzado en el idioma inglés y estoy empezando en el jápones. A la edad de 5 años empecé la escuela primaria, donde me desempeñé en el aprendizaje. En la secundaria perdí un poco el hilo de ser disciplinado y pasé a ser un poco más sociable, ya que no lo era mucho. Entrando a bachillerato, fue una de las etapas má duras de mi vida, obtuve mi primer trabajo y decidí cambiar mi horario de estudio a nocturno, terminando así mis estudios de bachillerato en modalidad nocturna. luego de medio año de trabajar en la empresa en la que me contrataron, tuve que renunciar debido a que gracias a los cada vez más exigentes horarios de ingreso " 
title_image: "https://scontent.fgye2-1.fna.fbcdn.net/v/t1.0-9/118249201_3198015596973236_7037746664810210779_n.jpg?_nc_cat=102&_nc_sid=8bfeb9&_nc_eui2=AeHx93rNN5dXY6gJE4KXhGF-P6lKPErMC38_qUo8SswLfyfX308vMJVrPBDmxJncoUVbbX9GpqESnvr7P1TI42Uw&_nc_ohc=RzMFOsfpVvMAX82l-Sj&_nc_ht=scontent.fgye2-1.fna&oh=c1e1c1849bfb649e6f79aba084fa5e16&oe=5F66B062"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  DiegJazm98
instagram_username: not_a_robot.maybe


# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>/Diego Carvajal Maridueña"


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
